# Generated by Django 5.1.4 on 2025-01-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
