# Generated by Django 5.1.4 on 2025-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_media', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
