# Generated by Django 5.1.4 on 2025-01-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_alter_people_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post', models.TextField(null=True)),
                ('image_post', models.ImageField(blank=True, upload_to='')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.people')),
            ],
        ),
    ]
