# Generated by Django 5.1.4 on 2025-01-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower_user_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following_user_id',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'following')},
        ),
    ]
